### ISSUE TITLE
saplikey_get_info error 'AnsibleModule_saplikey' object has no attribute 'cleanup_files'

### ISSUE THREAD

**Issue by guipaludo** [redhat-sap/rh_operations#62]
## Playbook
  - name: SAP License
    hosts: dev
    tasks:
      - name: Get License
        sap.sap_operations.saplikey_get_info:
          profile: "{{ '/sapmnt/' + sap_sid + '/profile/DEFAULT.PFL' }}"

##Error

The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1712838100.2343607-3483-256789826731396/AnsiballZ_saplikey_get_info.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1712838100.2343607-3483-256789826731396/AnsiballZ_saplikey_get_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1712838100.2343607-3483-256789826731396/AnsiballZ_saplikey_get_info.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py", line 149, in <module>
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py", line 137, in main
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py", line 98, in run_saplikey_command
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py", line 118, in fail_if_environment_not_set
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible/module_utils/basic.py", line 1552, in fail_json
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible/module_utils/basic.py", line 1476, in do_cleanup_files
AttributeError: [log.txt](https://github.com/redhat-sap/rh_operations/files/14946074/log.txt)
fatal: [vlxsapecd01]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.100.246 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1712838100.2343607-3483-256789826731396/AnsiballZ_saplikey_get_info.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1712838100.2343607-3483-256789826731396/AnsiballZ_saplikey_get_info.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1712838100.2343607-3483-256789826731396/AnsiballZ_saplikey_get_info.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py\", line 149, in <module>\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py\", line 137, in main\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py\", line 98, in run_saplikey_command\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py\", line 118, in fail_if_environment_not_set\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible/module_utils/basic.py\", line 1552, in fail_json\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_zathnie7/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible/module_utils/basic.py\", line 1476, in do_cleanup_files\r\nAttributeError: 'AnsibleModule_saplikey' object has no attribute 'cleanup_files'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by kksat** [comment]
I will take a look probably next week. Thank you for detailed error description.

What ansible / ansible-core version do you use? just provide output of 

```bash

ansible --version

```

do not forget to remove sensitive data - like username

**Comment by kksat** [comment]
Could you please also check module documentation 

https://docs.galaxy.saponrhel.org/collections/sap/sap_operations/saplikey_get_info_module.html#examples

I do not understand why do you want to use parameter "profile" with this module. Please explain what are you trying to achieve I might help with some code examples.

Module should be executed with <sid>adm not root. See link to examples above.

**Comment by guipaludo** [comment]
hello, thank you  for answer.

I tried to execute as you mentioned, changing the user, but now gives other error. "'AnsibleModule_saplikey' object has no attribute 'params'"

## Ansible version ##
[root@ansible ansible]# ansible --version
ansible [core 2.15.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules']
  ansible python module location = /root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True


## Task ##

      - name: Get License
        sap.sap_operations.saplikey_get_info:
        become: true
        become_user: ecdadm
        become_flags: '-i'


## Error ##

The full traceback is:
Traceback (most recent call last):
  File "/var/tmp/ansible-tmp-1712858373.8681993-1364-3719273351230/AnsiballZ_saplikey_get_info.py", line 107, in <module>
    _ansiballz_main()
  File "/var/tmp/ansible-tmp-1712858373.8681993-1364-3719273351230/AnsiballZ_saplikey_get_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/tmp/ansible-tmp-1712858373.8681993-1364-3719273351230/AnsiballZ_saplikey_get_info.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py", line 149, in <module>
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py", line 137, in main
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py", line 98, in run_saplikey_command
  File "/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py", line 120, in fail_if_environment_not_set
AttributeError: 'AnsibleModule_saplikey' object has no attribute 'params'
fatal: [vlxsapnfd01]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.100.243 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/var/tmp/ansible-tmp-1712858373.8681993-1364-3719273351230/AnsiballZ_saplikey_get_info.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/var/tmp/ansible-tmp-1712858373.8681993-1364-3719273351230/AnsiballZ_saplikey_get_info.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/var/tmp/ansible-tmp-1712858373.8681993-1364-3719273351230/AnsiballZ_saplikey_get_info.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py\", line 149, in <module>\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/modules/saplikey_get_info.py\", line 137, in main\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py\", line 98, in run_saplikey_command\r\n  File \"/tmp/ansible_sap.sap_operations.saplikey_get_info_payload_wowmythq/ansible_sap.sap_operations.saplikey_get_info_payload.zip/ansible_collections/sap/sap_operations/plugins/module_utils/saplikey.py\", line 120, in fail_if_environment_not_set\r\nAttributeError: 'AnsibleModule_saplikey' object has no attribute 'params'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by guipaludo** [comment]
Follow the evidence about command saplikey on target.

## saplikey ##
vlxsapecd01:ecdadm 52> saplikey pf=/sapmnt/ECD/profile/DEFAULT.PFL -get
SAP License Key Administration  -  Copyright (C) 2003 - 2016 SAP AG

System ID. . . . : ECD
Hardware Key . . : Q0052950004        (of this computer)
Installation No. : 0021004146
System No. . . . : 000000000850100169
Release. . . . . : 753
Software products: NetWeaver_HDB

## python target ##
vlxsapecd01:ecdadm 51> /usr/libexec/platform-python --version
Python 3.6.8

**Comment by kksat** [comment]
@guipaludo issue looks very strange to me - attribute 'params' is common ansible module attribute, same as method 'cleanup_files'.

Could you please check that your ansible is correctly installed - please reinstall it and try again. 
I see you are on IBM power system and ansible installed with pip - please try installing this package https://access.redhat.com/downloads/content/ansible-core/2.15.3-1.el8/ppc64le/fd431d51/package
or other ansible/ansible-core compatible package (ansible version >=2.15)

**Comment by kksat** [comment]
@guipaludo did you have a chance to try my suggestions? do you still have this issue? Thank you for your reply

**Comment by kksat** [comment]
@guipaludo please reply, otherwise I will have to close this stale issue

**Comment by kksat** [comment]
Consider this issue stalled, closing
